### ISSUE TITLE
Is there a way to update the system prompt in the react sdk? 

### ISSUE THREAD

**Issue by akdeb** [HumeAI/empathic-voice-api-js#218]
Does `@humeai/voice-react` have an easy way of updating the system prompt? Couldn't find it in the docs and the index.d.ts

**Comment by zachkrall** [comment]
Hi @akdeb! You can pass a `sessionSettings` object to `VoiceProvider` to change the system prompt.

```tsx
<VoiceProvider
	auth={{ 
		type: 'apiKey', 
		value: apiKey
	}}
	sessionSettings={{
		'systemPrompt': 'YOUR SYSTEM PROMPT HERE'
	}}
>
</VoiceProvider>
```

You can find other possible values for `sessionSettings` here: https://dev.hume.ai/reference/empathic-voice-interface-evi/chat/chat#send

**Comment by akdeb** [comment]
Makes sense thanks @zachkrall!
