### ISSUE TITLE
Functions in from useVoice are no longer stable between re-renders in @humeai/voice-react 0.1.15

### ISSUE THREAD

**Issue by michalmo** [HumeAI/empathic-voice-api-js#269]
Something in version 0.1.15 (probably #265) has changed the behaviour of the functions returned by the `useVoice` hook. The references returned are now changing with each render (so as often as `fft` changes).

Specifically in my code effects such as this are being called each render:

```typescript
  const { readyState, sendUserInput } = useVoice();

  useEffect(() => {
    if (readyState === VoiceReadyState.OPEN) {
      sendUserInput(...);
    }
  }, [readyState, sendUserInput]);
```

**Comment by yinishi** [comment]
The fix is available in beta 0.1.16-beta.2 and will be included in the upcoming 0.1.16 release.
