### ISSUE TITLE
Using VoiceProvider sessionSettings prop causes connection to fail with an exception

### ISSUE THREAD

**Issue by michalmo** [HumeAI/empathic-voice-api-js#270]
Session is immediately closed with exception type `socket_error` and message "We could not connect to the voice. Please try again."

The error originates here https://github.com/HumeAI/empathic-voice-api-js/blob/v0.1.15/packages/react/src/lib/VoiceProvider.tsx#L302-L305 and it appears that `readyState` is not yet `OPEN` (see https://github.com/HumeAI/empathic-voice-api-js/blob/v0.1.15/packages/react/src/lib/useVoiceClient.ts#L215-L217).

**Comment by yinishi** [comment]
The fix is available in beta 0.1.16-beta.2 and will be included in the upcoming 0.1.16 release.
